# Generated by Django 4.2 on 2026-04-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
