# Generated by Django 4.2 on 2026-04-22 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_order_shipping_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ xử lý'), ('Processing', 'Đang đóng gói'), ('Shipped', 'Đang giao'), ('Delivered', 'Đã nhận hàng'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='app.order')),
            ],
        ),
    ]
