# Generated by Django 4.2 on 2026-05-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sold_count',
            field=models.IntegerField(default=0),
        ),
    ]
