# Generated by Django 4.2 on 2026-05-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_book_sold_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSaleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Bật flash sale')),
                ('discount_percent', models.PositiveIntegerField(default=30, help_text='Nhập số nguyên, VD: 30 → giảm 30%', verbose_name='% giảm giá')),
                ('start_hour', models.PositiveIntegerField(default=20, verbose_name='Giờ bắt đầu (0-23)')),
                ('start_minute', models.PositiveIntegerField(default=0, verbose_name='Phút bắt đầu (0-59)')),
                ('end_hour', models.PositiveIntegerField(default=22, verbose_name='Giờ kết thúc (0-23)')),
                ('end_minute', models.PositiveIntegerField(default=0, verbose_name='Phút kết thúc (0-59)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình Flash Sale',
            },
        ),
    ]
