# Generated by Django 6.0.3 on 2026-06-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_flashsaleconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã coupon')),
                ('discount_percent', models.IntegerField(default=10, verbose_name='Giảm (%)')),
                ('valid_until', models.DateField(verbose_name='Hết hạn')),
                ('max_uses', models.IntegerField(default=100, verbose_name='Số lần dùng tối đa')),
                ('used_count', models.IntegerField(default=0, verbose_name='Đã dùng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
            },
        ),
        migrations.RemoveField(
            model_name='flashsaleconfig',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền giảm'),
        ),
        migrations.AlterField(
            model_name='flashsaleconfig',
            name='discount_percent',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='flashsaleconfig',
            name='end_hour',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='flashsaleconfig',
            name='end_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flashsaleconfig',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flashsaleconfig',
            name='start_hour',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='flashsaleconfig',
            name='start_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ xử lý'), ('Confirmed', 'Đã xác nhận'), ('Shipped', 'Đang giao'), ('Received', 'Đã nhận hàng'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='app.coupon', verbose_name='Mã giảm giá'),
        ),
    ]
